name: 节点小宝
version: "3.0.5"
slug: jdxb
description: "A Home Assistant add-on for jdxb service. 这是一个节点小宝客户端"
url: "https://github.com/wuwweizn/wwzn-china/"
codenotary: "wuweizhineng@163.com"

arch:
  - amd64
  - aarch64

startup: services
ingress: true
ingress_port: 9118
image: "ghcr.nju.edu.cn/wuwweizn/jdxb-{arch}"
init: false
hassio_role: manager
panel_icon: mdi:server-network

ports:
  "9118/tcp": 9118

devices:
  - /dev/net/tun

boot: manual
restart: always
host_network: true
webui: "http://[HOST]:[PORT:9118]"
