---
build_from:
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base-debian:bookworm
  amd64: gghcr.nju.edu.cn/home-assistant/amd64-base-debian:bookworm
  armhf: ghcr.nju.edu.cn/home-assistant/armhf-base-debian:bookworm
  armv7: ghcr.nju.edu.cn/home-assistant/armv7-base-debian:bookworm
  i386: ghcr.nju.edu.cn/home-assistant/i386-base-debian:bookworm
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  LIBWEBSOCKET_VERSION: 4.3.3
  MOSQUITTO_VERSION: 2.0.21
  MOSQUITTO_AUTH_VERSION: 2.1.0
