build_from:
  aarch64: "ghcr.nju.edu.cn/home-assistant/aarch64-base-python:3.12-alpine3.20"
  amd64: "ghcr.nju.edu.cn/home-assistant/amd64-base-python:3.12-alpine3.20"
  armhf: "ghcr.nju.edu.cn/home-assistant/armhf-base-python:3.12-alpine3.20"
  armv7: "ghcr.nju.edu.cn/home-assistant/armv7-base-python:3.12-alpine3.20"
  i386: "ghcr.nju.edu.cn/home-assistant/i386-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "HACS极速版: 安装器"
  org.opencontainers.image.description: "安装HACS极速版"
  org.opencontainers.image.source: "https://ghproxy.link/github.com/hacs-china/addons"
  org.opencontainers.image.licenses: "MIT License"
